title: Ok to Roam
description: My Blog

url: http://oktoroam.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
# - title: Contact
#   url: /contact

# social:
#   github: 
#   twitter: 
#   facebook: 
#   email: 

google_analytics: "UA-74836913-2"

